export const Icon = {
  MAIN_LOGO: require("../assets/icon/MainLogo.png"),
  Admin_logo: require("../assets/icon/Admin.png"),
  Clock_logo: require("../assets/icon/Clock.svg").default,
  Calender_logo: require("../assets/icon/Calender.png"),
  Email_logo: require("../assets/icon/email.png"),
  Facebook_logo: require("../assets/icon/Icon awesome-facebook-f.png"),
  HODDI_logo: require("../assets/icon/Hoodi.png"),
  Inst_logo: require("../assets/icon/instagram.png"),
  LINKDAN_logo: require("../assets/icon/Linkdan.png"),
  Tweeter_logo: require("../assets/icon/Tweeter.png"),
  Location_logo: require("../assets/icon/location-sharp.png"),
  TShirt_logo: require("../assets/icon/Tshirt.png"),
  Bike_logo: require("../assets/icon/stationary-bike.png"),
  Trouser_logo: require("../assets/icon/trousers.png"),
  Situp_logo: require("../assets/icon/sit-up.png"),
  Phone_Red_logo: require("../assets/icon/phone.png"),
  Phone_logo: require("../assets/icon/phone-alt.png"),
  WorkMachine_logo: require("../assets/icon/outline.png"),
  Medican_logo: require("../assets/icon/medicine.png"),
  Massage_logo: require("../assets/icon/MassageBox.png"),
  Mandum_logo: require("../assets/icon/ManwithDump.png"),
  Search_logo: require("../assets/icon/Icon map-search.png"),
  FaceBookRed_logo: require("../assets/icon/Facbook.png"),
  Inhandthumbal_logo: require("../assets/icon/Group 103.png"),
  Google_logo: require("../assets/icon/google-plus-g.png"),
  Clipboadr_logo: require("../assets/icon/clipboard.svg").default,
  ManWorkOut: require("../assets/icon/WorkOut.svg").default,
  CAP_logo: require("../assets/icon/Cap.png"),
  Body_logo: require("../assets/icon/Body.png"),
  Youtube_logo: require("../assets/icon/youtube.png"),
  Navbar_logo: require("../assets/icon/Group5.svg").default,
  Navbar_logo2: require("../assets/icon/Group 5.svg").default,
  Left_Arrow: require("../assets/icon/left-arrow.svg").default,
  Right_Arrow: require("../assets/icon/Right-arrow.svg").default,
  GYM_Logo: require("../assets/icon/GymLogo.svg").default,
  Close_Logo: require("../assets/icon/Close.svg").default,
};
// export Icon;
