export const Images = {
  ProtinSmall: require("../assets/imges/Smallprotian.png"),
  Wife_husband: require("../assets/imges/WifeHusband.png"),
  WiHu_background: require("../assets/imges/WifeBack.png"),
  Card_1: require("../assets/imges/Warkout1.png"),
  Card_2: require("../assets/imges/Warkout2.png"),
  Card_3: require("../assets/imges/Warkout3.png"),
  Hero_back: require("../assets/imges/herotopback.png"),
  Four_img: require("../assets/imges/Fourimg.png"),
  Black_backGround: require("../assets/imges/protoanBox_Backgriond.png"),
  Title_img: require("../assets/imges/Title_img.png"),
  Login_back: require("../assets/imges/loginBackGround.png"),
  Hero_Back_top0: require("../assets/imges/IMAGE0.jpg"),
  Hero_Back_top1: require("../assets/imges/IMAGE1.jpg"),
  Hero_Back_top2: require("../assets/imges/IMAGE2.jpg"),
  Hero_Back_top3: require("../assets/imges/IMAGE3.jpg"),
  Hero_Back_top4: require("../assets/imges/IMAGE4.jpg"),
  Text_outerBorder: require("../assets/imges/Path 57.png"),
  Btn_outerBorder: require("../assets/imges/Path 58.png"),
  Video_back1: require("../assets/imges/VideoBack.png"),
  Video_back2: require("../assets/imges/protinBoxBack.png"),
  ProtinBIg: require("../assets/imges/BigProtianbox.png"),
};
